/**
 * SMART CITY GUIDE - PAN-INDIA MOCK DATASET
 * Complete coverage of 28 States & 8 UTs, tier 1/2/3 cities, famous streets, and local gullies.
 */
const SMART_CITY_MOCK = {
    statesAndCities: [
        { state: "All India", cities: ["All Cities"] },
        { state: "Delhi (NCR)", cities: ["New Delhi", "North Delhi", "South Delhi", "Old Delhi", "Noida", "Gurugram"] },
        { state: "Maharashtra", cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"] },
        { state: "Rajasthan", cities: ["Jaipur", "Udaipur", "Jodhpur", "Jaisalmer", "Pushkar"] },
        { state: "Uttar Pradesh", cities: ["Varanasi", "Lucknow", "Agra", "Ayodhya", "Prayagraj", "Mathura"] },
        { state: "Karnataka", cities: ["Bengaluru", "Mysuru", "Mangaluru", "Hampi", "Hubli"] },
        { state: "West Bengal", cities: ["Kolkata", "Darjeeling", "Siliguri", "Howrah"] },
        { state: "Tamil Nadu", cities: ["Chennai", "Madurai", "Coimbatore", "Rameswaram", "Ooty"] },
        { state: "Telangana", cities: ["Hyderabad", "Warangal", "Nizamabad"] },
        { state: "Kerala", cities: ["Kochi", "Thiruvananthapuram", "Munnar", "Alappuzha", "Kozhikode"] },
        { state: "Punjab", cities: ["Amritsar", "Ludhiana", "Jalandhar", "Patiala"] },
        { state: "Madhya Pradesh", cities: ["Indore", "Bhopal", "Gwalior", "Ujjain", "Jabalpur"] },
        { state: "Gujarat", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Kutch"] },
        { state: "Himachal Pradesh", cities: ["Shimla", "Manali", "Dharamshala", "Kullu", "Spiti"] },
        { state: "Goa", cities: ["Panaji", "Margao", "Vasco da Gama", "Calangute"] },
        { state: "Jammu & Kashmir", cities: ["Srinagar", "Jammu", "Gulmarg", "Pahalgam"] },
        { state: "Assam", cities: ["Guwahati", "Kaziranga", "Tezpur", "Silchar"] },
        { state: "Uttarakhand", cities: ["Dehradun", "Rishikesh", "Haridwar", "Nainital", "Mussoorie"] },
        { state: "Bihar", cities: ["Patna", "Gaya", "Nalanda", "Bhagalpur"] },
        { state: "Odisha", cities: ["Bhubaneswar", "Puri", "Cuttack", "Konark"] },
        { state: "Andhra Pradesh", cities: ["Visakhapatnam", "Vijayawada", "Tirupati"] },
        { state: "Haryana", cities: ["Chandigarh", "Faridabad", "Panipat"] },
        { state: "Puducherry", cities: ["Pondicherry", "Auroville"] },
        { state: "Sikkim", cities: ["Gangtok", "Pelling", "Namchi"] },
        { state: "Meghalaya", cities: ["Shillong", "Cherrapunji", "Dawki"] }
    ],

    categories: [
        { id: 1, name: "Heritage & Monuments", code: "HERITAGE", icon: "fa-landmark" },
        { id: 2, name: "Parks, Ghats & Lakes", code: "PARKS", icon: "fa-tree" },
        { id: 3, name: "Museums & Science", code: "MUSEUMS", icon: "fa-palette" },
        { id: 4, name: "Food & Night Streets", code: "FOOD", icon: "fa-utensils" },
        { id: 5, name: "Smart Transit & EV", code: "TRANSIT", icon: "fa-subway" },
        { id: 6, name: "Artisan Bazaars & Streets", code: "SHOPPING", icon: "fa-shopping-bag" }
    ],

    places: [
        // --- DELHI NCR ---
        {
            id: 1,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "Delhi (NCR)",
            city: "New Delhi",
            streetName: "Netaji Subhash Marg, Chandni Chowk",
            title: "Red Fort (Lal Qila) & Heritage Corridor",
            tagline: "17th Century Mughal Citadel & Laser Sound Show",
            description: "Monumental red sandstone citadel built by Emperor Shah Jahan. Houses historical war museums, royal bath pavilions, and a grand sound & light show.",
            zone: "North Delhi",
            address: "Netaji Subhash Marg, Chandni Chowk, New Delhi",
            pincode: "110006",
            lat: 28.6562,
            lng: 77.2410,
            entryFee: 50.00,
            openingHours: "08:00 AM - 07:00 PM",
            contactPhone: "+91-11-23270000",
            imageUrl: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.85,
            totalReviews: 1420,
            isFeatured: true,
            facilities: ["Audio Guide", "Wheelchair Accessible", "EV Parking", "Cafeteria", "Locker Room"],
            reviews: [
                { author: "Aarav Sharma", rating: 5, date: "2 days ago", comment: "The laser show at 7 PM is breathtaking! Very clean premises and seamless digital entry." }
            ]
        },
        {
            id: 2,
            categoryId: 4,
            categoryName: "Food & Night Streets",
            state: "Delhi (NCR)",
            city: "New Delhi",
            streetName: "Gali Paranthe Wali, Chandni Chowk",
            title: "Paranthe Wali Gali & Sweet Alley",
            tagline: "Centuries-Old Traditional Culinary Lane",
            description: "World-famous narrow gully in Old Delhi serving over 30 varieties of crisp, golden deep-fried paranthas, sweet rabri, and chilled matka lassi since 1872.",
            zone: "Central Delhi",
            address: "Gali Paranthe Wali, Near Katra Neel, Chandni Chowk",
            pincode: "110006",
            lat: 28.6558,
            lng: 77.2305,
            entryFee: 0.00,
            openingHours: "09:00 AM - 11:30 PM",
            contactPhone: "+91-11-23265544",
            imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.80,
            totalReviews: 3100,
            isFeatured: true,
            facilities: ["Pure Ghee Dishes", "Digital Payments", "Heritage Ambience"],
            reviews: [
                { author: "Emily Watson", rating: 5, date: "4 days ago", comment: "The food variety is unreal! Extremely vibrant energy and delicious flavors." }
            ]
        },
        {
            id: 3,
            categoryId: 6,
            categoryName: "Artisan Bazaars & Streets",
            state: "Delhi (NCR)",
            city: "New Delhi",
            streetName: "Sri Aurobindo Marg, INA",
            title: "Dilli Haat Crafts & Pan-India Food Village",
            tagline: "Open-Air Artisan Bazaar Representing All 28 States",
            description: "Government-accredited craft emporium where master weavers and rural artisans demonstrate live terracotta pottery, brass sculpting, and handloom silks.",
            zone: "South Delhi",
            address: "Opposite INA Market, Sri Aurobindo Marg, New Delhi",
            pincode: "110023",
            lat: 28.5732,
            lng: 77.2085,
            entryFee: 30.00,
            openingHours: "10:30 AM - 10:00 PM",
            contactPhone: "+91-11-26119055",
            imageUrl: "https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.70,
            totalReviews: 920,
            isFeatured: true,
            facilities: ["Authentic State Food Stalls", "Wheelchair Friendly", "Cashless UPI"],
            reviews: [
                { author: "Kavita Rao", rating: 5, date: "1 week ago", comment: "Direct purchase from master artisans without middlemen!" }
            ]
        },

        // --- MAHARASHTRA (MUMBAI & PUNE) ---
        {
            id: 4,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "Maharashtra",
            city: "Mumbai",
            streetName: "Netaji Subhash Chandra Bose Road, Marine Drive",
            title: "Marine Drive & Queen's Necklace Promenade",
            tagline: "3.6-km Coastal Boulevard & Sunset Promenade",
            description: "World-famous seaside promenade curving along the Arabian Sea coast. Features Art Deco architecture, walking trails, and magnificent evening city skylines.",
            zone: "South Mumbai",
            address: "Netaji Subhash Chandra Bose Road, Chowpatty to Nariman Point, Mumbai",
            pincode: "400020",
            lat: 18.9432,
            lng: 72.8230,
            entryFee: 0.00,
            openingHours: "24 Hours Open",
            contactPhone: "+91-22-22820000",
            imageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.90,
            totalReviews: 4800,
            isFeatured: true,
            facilities: ["Sea Breeze Walking Promenade", "Night Patrolling", "Clean Public Seating"],
            reviews: [
                { author: "Rohan Varma", rating: 5, date: "Yesterday", comment: "The ocean view at night with the lit-up necklace curve is pure magic." }
            ]
        },
        {
            id: 5,
            categoryId: 4,
            categoryName: "Food & Night Streets",
            state: "Maharashtra",
            city: "Mumbai",
            streetName: "Khau Galli, Vallabh Bagh Lane, Ghatkopar East",
            title: "Ghatkopar Khau Galli & Fusion Street",
            tagline: "Mumbai's Renowned 100+ Street Food Corridor",
            description: "Electrifying food street celebrated for 1000-cheese burst dosas, remixed frankies, ice baraf golas, and sizzling pav bhaji.",
            zone: "Central Mumbai",
            address: "Vallabh Bagh Lane, Ghatkopar East, Mumbai",
            pincode: "400077",
            lat: 19.0850,
            lng: 72.9080,
            entryFee: 0.00,
            openingHours: "02:00 PM - 01:30 AM",
            contactPhone: "+91-22-25010000",
            imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.75,
            totalReviews: 2300,
            isFeatured: false,
            facilities: ["Late Night Dining", "UPI Payments", "Pure Vegetarian Options"]
        },
        {
            id: 6,
            categoryId: 6,
            categoryName: "Artisan Bazaars & Streets",
            state: "Maharashtra",
            city: "Pune",
            streetName: "Fergusson College Road (FC Road)",
            title: "FC Road & Deccan Shopping Boulevard",
            tagline: "Lively Youth Fashion, Bookshops & Irani Cafes",
            description: "Vibrant pedestrian avenue in Pune packed with bookstores, trendy fashion stalls, antique leather footwear, and heritage Irani bakery cafes.",
            zone: "Shivajinagar",
            address: "Fergusson College Road, Deccan Gymkhana, Pune",
            pincode: "411004",
            lat: 18.5246,
            lng: 73.8415,
            entryFee: 0.00,
            openingHours: "10:00 AM - 11:00 PM",
            contactPhone: "+91-20-25650000",
            imageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.65,
            totalReviews: 1250,
            isFeatured: false,
            facilities: ["Heritage Cafes", "Street Shopping", "Bicycle Sharing Docks"]
        },

        // --- RAJASTHAN (JAIPUR & UDAIPUR) ---
        {
            id: 7,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "Rajasthan",
            city: "Jaipur",
            streetName: "Hawa Mahal Road, Badi Chaupar, Johari Bazaar",
            title: "Hawa Mahal & Johari Heritage Bazaar",
            tagline: "Palace of Winds with 953 Intricately Carved Jharokhas",
            description: "1799 pink sandstone architectural wonder overlooking Johari Bazaar. Renowned for authentic Kundan jewelry, Meenakari enamel, and block-printed textiles.",
            zone: "Heritage Core",
            address: "Badi Chaupar, Hawa Mahal Marg, Jaipur",
            pincode: "302002",
            lat: 26.9239,
            lng: 75.8267,
            entryFee: 50.00,
            openingHours: "09:00 AM - 05:30 PM",
            contactPhone: "+91-141-2618862",
            imageUrl: "https://images.unsplash.com/photo-1603228254119-e6a528dc5686?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.88,
            totalReviews: 3850,
            isFeatured: true,
            facilities: ["Tourist Guides", "Rooftop Cafes", "Handicraft Emporiums"]
        },
        {
            id: 8,
            categoryId: 2,
            categoryName: "Parks, Ghats & Lakes",
            state: "Rajasthan",
            city: "Udaipur",
            streetName: "Gangaur Ghat Marg, Old City",
            title: "Lake Pichola & Gangaur Ghat Promenade",
            tagline: "Serene Royal Lake with Sunset Boating & Bagore Ki Haveli",
            description: "Picturesque freshwater lake surrounded by the City Palace, marble temples, and evening Rajasthani folk dance performances at Bagore Ki Haveli.",
            zone: "Old City Zone",
            address: "Gangaur Ghat Marg, Near Bagore Ki Haveli, Udaipur",
            pincode: "313001",
            lat: 24.5797,
            lng: 73.6800,
            entryFee: 30.00,
            openingHours: "06:00 AM - 10:00 PM",
            contactPhone: "+91-294-2419010",
            imageUrl: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.92,
            totalReviews: 2900,
            isFeatured: true,
            facilities: ["Solar Boating Jetties", "Live Folk Performances", "Heritage Ghats"]
        },

        // --- UTTAR PRADESH (VARANASI & LUCKNOW) ---
        {
            id: 9,
            categoryId: 2,
            categoryName: "Parks, Ghats & Lakes",
            state: "Uttar Pradesh",
            city: "Varanasi",
            streetName: "Dashashwamedh Ghat Road, Godowlia",
            title: "Dashashwamedh Ghat & Ganga Maha Aarti Corridor",
            tagline: "World's Most Ancient Spiritual Waterfront & Silk Alleys",
            description: "The premier spiritual ghat of Kashi on the river Ganga. Experience the divine 7-lamp evening Maha Aarti, surrounded by narrow Banarasi silk weaver alleys.",
            zone: "Heritage Ghats",
            address: "Dashashwamedh Ghat Road, Godowlia, Varanasi",
            pincode: "221001",
            lat: 25.3076,
            lng: 83.0104,
            entryFee: 0.00,
            openingHours: "24 Hours Open (Aarti 06:45 PM)",
            contactPhone: "+91-542-2505000",
            imageUrl: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.96,
            totalReviews: 5600,
            isFeatured: true,
            facilities: ["Boat Rides", "Silk Weaving Workshops", "Spiritual Heritage Walk"]
        },
        {
            id: 10,
            categoryId: 4,
            categoryName: "Food & Night Streets",
            state: "Uttar Pradesh",
            city: "Lucknow",
            streetName: "Nazirabad Road, Aminabad Market",
            title: "Aminabad Food Street & Tunday Kababi Gali",
            tagline: "Historic Royal Awadhi Kebabs & Chikankari Bazaars",
            description: "Century-old culinary street celebrated for legendary 160-spice melt-in-mouth Galawati kebabs, Mughlai parathas, and authentic royal Lucknowi Chikankari embroidery.",
            zone: "Old City Zone",
            address: "Nazirabad Road, Aminabad, Lucknow",
            pincode: "226018",
            lat: 26.8450,
            lng: 80.9250,
            entryFee: 0.00,
            openingHours: "11:00 AM - 12:30 AM",
            contactPhone: "+91-522-2620000",
            imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.85,
            totalReviews: 4100,
            isFeatured: true,
            facilities: ["Royal Awadhi Cuisine", "Chikan Handloom Stalls", "Air Conditioned Dining"]
        },

        // --- KARNATAKA (BENGALURU) ---
        {
            id: 11,
            categoryId: 2,
            categoryName: "Parks, Ghats & Lakes",
            state: "Karnataka",
            city: "Bengaluru",
            streetName: "Mavalli, Lalbagh Fort Road",
            title: "Lalbagh Botanical Garden & Glass House",
            tagline: "240-Acre Heritage Oasis with 1,800+ Exotic Flora",
            description: "Historic botanical sanctuary founded by Hyder Ali. Features the London Crystal Palace-inspired Glass House, ancient peninsular gneiss rock, and serene lotus lake.",
            zone: "South Bengaluru",
            address: "Lalbagh Fort Road, Mavalli, Bengaluru",
            pincode: "560004",
            lat: 12.9507,
            lng: 77.5848,
            entryFee: 25.00,
            openingHours: "06:00 AM - 07:00 PM",
            contactPhone: "+91-80-26570181",
            imageUrl: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.80,
            totalReviews: 2600,
            isFeatured: true,
            facilities: ["Flower Shows", "Battery Buggy Rides", "Solar Trees", "Lake Trail"]
        },
        {
            id: 12,
            categoryId: 4,
            categoryName: "Food & Night Streets",
            state: "Karnataka",
            city: "Bengaluru",
            streetName: "Old Tharagupet, Sajjan Rao Circle, VV Puram",
            title: "VV Puram Thindi Beedi (Food Street)",
            tagline: "Famous Pure Vegetarian Street Food Hub with 30+ Stalls",
            description: "The gastronomic pulse of South Bengaluru. Packed every evening with stalls serving crisp Butter Masala Dosas, Congress Buns, Akki Rottis, and filter coffee.",
            zone: "Basavanagudi",
            address: "Old Tharagupet, VV Puram, Bengaluru",
            pincode: "560004",
            lat: 12.9520,
            lng: 77.5750,
            entryFee: 0.00,
            openingHours: "05:30 PM - 11:30 PM",
            contactPhone: "+91-80-22440000",
            imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.82,
            totalReviews: 3400,
            isFeatured: true,
            facilities: ["Pure Vegetarian", "Fast Casual Counters", "UPI QR Docks"]
        },

        // --- WEST BENGAL (KOLKATA) ---
        {
            id: 13,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "West Bengal",
            city: "Kolkata",
            streetName: "1, Queen's Way, Maidan",
            title: "Victoria Memorial Hall & Royal Gardens",
            tagline: "Grand Makrana White Marble Monument & Museum",
            description: "Iconic architectural landmark dedicated to Queen Victoria, showcasing rare British-era paintings, statues, manicured fountains, and horse-drawn carriage rides.",
            zone: "Central Kolkata",
            address: "1, Queen's Way, Maidan, Kolkata",
            pincode: "700071",
            lat: 22.5448,
            lng: 88.3426,
            entryFee: 30.00,
            openingHours: "10:00 AM - 06:00 PM",
            contactPhone: "+91-33-22231890",
            imageUrl: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.88,
            totalReviews: 3700,
            isFeatured: true,
            facilities: ["Heritage Museum", "Laser Sound Show", "Tramway Stop Nearby"]
        },
        {
            id: 14,
            categoryId: 4,
            categoryName: "Food & Night Streets",
            state: "West Bengal",
            city: "Kolkata",
            streetName: "Mother Teresa Sarani, Park Street",
            title: "Park Street Heritage Cafe & Dining Corridor",
            tagline: "Kolkata's High Street for Legendary Jazz, Kathi Rolls & Bakeries",
            description: "Colonial-era culinary boulevard famous for iconic continental bistros, Flurys tea room, live jazz music, authentic Chelo kebabs, and festive lights.",
            zone: "Central Kolkata",
            address: "Park Street, Mother Teresa Sarani, Kolkata",
            pincode: "700016",
            lat: 22.5510,
            lng: 88.3530,
            entryFee: 0.00,
            openingHours: "11:00 AM - 12:00 AM",
            contactPhone: "+91-33-22290000",
            imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.82,
            totalReviews: 2900,
            isFeatured: true,
            facilities: ["Historic Jazz Cafes", "Late Night Dining", "Pedestrian Walkways"]
        },

        // --- TAMIL NADU (CHENNAI) ---
        {
            id: 15,
            categoryId: 2,
            categoryName: "Parks, Ghats & Lakes",
            state: "Tamil Nadu",
            city: "Chennai",
            streetName: "Kamarajar Salai, Triplicane",
            title: "Marina Beach Promenade & Lighthouse",
            tagline: "World's Second Longest Natural Urban Beach (13 km)",
            description: "Expansive sandy shoreline along the Bay of Bengal featuring statues of Tamil scholars, coastal horse rides, crispy sundal stalls, and a high-tech viewing lighthouse.",
            zone: "East Coast Zone",
            address: "Kamarajar Salai, Triplicane, Chennai",
            pincode: "600005",
            lat: 13.0499,
            lng: 80.2824,
            entryFee: 0.00,
            openingHours: "24 Hours Open",
            contactPhone: "+91-44-25380000",
            imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.70,
            totalReviews: 4200,
            isFeatured: true,
            facilities: ["Lighthouse Elevator", "Fresh Seafood Counters", "Sea Breeze Walk"]
        },

        // --- TELANGANA (HYDERABAD) ---
        {
            id: 16,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "Telangana",
            city: "Hyderabad",
            streetName: "Charminar Road, Chudi Bazaar",
            title: "Charminar & Laad Bazaar Pearl Street",
            tagline: "1591 Monument & World Famous Lacquer Bangle Alley",
            description: "Four grand arches built by Qutb Shahi dynasty overlooking the vibrant Laad Bazaar, renowned for handmade lacquer bangles, Basra pearls, and Osmania biscuits with Irani chai.",
            zone: "Old City Zone",
            address: "Charminar Road, Char Kaman, Hyderabad",
            pincode: "500002",
            lat: 17.3616,
            lng: 78.4747,
            entryFee: 25.00,
            openingHours: "09:00 AM - 05:30 PM",
            contactPhone: "+91-40-24520000",
            imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.86,
            totalReviews: 4400,
            isFeatured: true,
            facilities: ["Pearl Markets", "Irani Chai Kiosks", "Heritage Night Lighting"]
        },

        // --- KERALA (KOCHI) ---
        {
            id: 17,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "Kerala",
            city: "Kochi",
            streetName: "Princess Street, Fort Kochi",
            title: "Fort Kochi Princess Street & Chinese Fishing Nets",
            tagline: "Portuguese & Dutch Colonial Alleys & Seaside Nets",
            description: "Charming cobblestone alley lined with Dutch villas, spice warehouses, vibrant art cafes, and cantilevered Chinese fishing nets along the Arabian sea beach.",
            zone: "Coastal Zone",
            address: "Princess Street, Fort Kochi, Kochi",
            pincode: "682001",
            lat: 9.9650,
            lng: 76.2420,
            entryFee: 0.00,
            openingHours: "24 Hours Open",
            contactPhone: "+91-484-2216500",
            imageUrl: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.84,
            totalReviews: 2100,
            isFeatured: true,
            facilities: ["Spice Markets", "Art Biennial Venues", "Sunset Ferry"]
        },

        // --- PUNJAB (AMRITSAR) ---
        {
            id: 18,
            categoryId: 1,
            categoryName: "Heritage & Monuments",
            state: "Punjab",
            city: "Amritsar",
            streetName: "Heritage Street, Katra Ahluwalia",
            title: "Sri Harmandir Sahib (Golden Temple) & Heritage Street",
            tagline: "Sacred Gilded Sanctuary & Cobblestone Cultural Boulevard",
            description: "Gleaming golden temple floating in the sacred Amrit Sarovar. The pedestrian Heritage Street features Punjabi phulkari crafts, Jutti stalls, and 24x7 Langar hall.",
            zone: "Walled City",
            address: "Heritage Street, Katra Ahluwalia, Amritsar",
            pincode: "143006",
            lat: 31.6200,
            lng: 74.8765,
            entryFee: 0.00,
            openingHours: "24 Hours Open",
            contactPhone: "+91-183-2553957",
            imageUrl: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.98,
            totalReviews: 8900,
            isFeatured: true,
            facilities: ["Free Community Langar", "Luggage Cloakroom", "24x7 Electric Shuttles"]
        },

        // --- MADHYA PRADESH (INDORE) ---
        {
            id: 19,
            categoryId: 4,
            categoryName: "Food & Night Streets",
            state: "Madhya Pradesh",
            city: "Indore",
            streetName: "56 Dukan Street, New Palasia",
            title: "Chhappan Dukan (56 Shops) Clean Food Plaza",
            tagline: "India's Cleanest FSSAI Certified Street Food Street",
            description: "Renowned culinary street with exactly 56 specialty shops serving piping hot Indori Poha Jalebi, Johnny Hotdog, Johri Shikanji, and khopra patties.",
            zone: "Central Indore",
            address: "New Palasia, 56 Dukan Street, Indore",
            pincode: "452001",
            lat: 22.7244,
            lng: 75.8839,
            entryFee: 0.00,
            openingHours: "06:00 AM - 11:00 PM",
            contactPhone: "+91-731-2530000",
            imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.90,
            totalReviews: 3900,
            isFeatured: true,
            facilities: ["Zero Plastic Zone", "Digital UPI", "FSSAI Clean Street Badge"]
        },

        // --- HIMACHAL PRADESH (SHIMLA) ---
        {
            id: 20,
            categoryId: 2,
            categoryName: "Parks, Ghats & Lakes",
            state: "Himachal Pradesh",
            city: "Shimla",
            streetName: "The Mall Road & The Ridge",
            title: "The Ridge & Mall Road Alpine Promenade",
            tagline: "Vehicle-Free Himalayan High Street with Panoramic Peaks",
            description: "Scenic mountain boulevard overlooking the snow-clad Pir Panjal ranges. Features neo-Gothic Christ Church, Tudor-style library, and Himachali woolen stalls.",
            zone: "Himalayan Ridge",
            address: "The Mall Road, Near Scandal Point, Shimla",
            pincode: "171001",
            lat: 31.1048,
            lng: 77.1734,
            entryFee: 0.00,
            openingHours: "08:00 AM - 10:30 PM",
            contactPhone: "+91-177-2651000",
            imageUrl: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.88,
            totalReviews: 3100,
            isFeatured: true,
            facilities: ["No Vehicles Zone", "Panoramic Himalayan Telescope", "Heated Cafes"]
        },

        // --- GOA (PANAJI) ---
        {
            id: 21,
            categoryId: 6,
            categoryName: "Artisan Bazaars & Streets",
            state: "Goa",
            city: "Panaji",
            streetName: "Rua 31 de Janeiro, Fontainhas",
            title: "Fontainhas Latin Quarter & Portuguese Street",
            tagline: "UNESCO Heritage Alleys with Pastel-Colored Colonial Mansions",
            description: "Asia's oldest Latin quarter featuring narrow cobblestone streets, red-tiled roofed Portuguese villas, traditional bakeries, and live fado music venues.",
            zone: "Heritage Panaji",
            address: "Rua 31 de Janeiro, Fontainhas, Panaji, Goa",
            pincode: "403001",
            lat: 15.4989,
            lng: 73.8315,
            entryFee: 0.00,
            openingHours: "24 Hours Open",
            contactPhone: "+91-832-2420000",
            imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80",
            ratingAvg: 4.82,
            totalReviews: 1950,
            isFeatured: true,
            facilities: ["Heritage Photo Walks", "Art Galleries", "Portuguese Bakeries"]
        }
    ],

    emergencyFacilities: [
        {
            id: 1,
            facilityName: "AIIMS Apex Multi-Specialty Government Hospital",
            type: "HOSPITAL",
            state: "Delhi (NCR)",
            city: "New Delhi",
            streetName: "Sri Aurobindo Marg, Ansari Nagar",
            zone: "South Delhi",
            address: "Ansari Nagar, Sri Aurobindo Marg, New Delhi",
            pincode: "110029",
            lat: 28.5672,
            lng: 77.2100,
            emergencyContact: "102 / +91-11-26588500",
            ambulanceContact: "+91-11-26588700",
            availableIcuBeds: 54,
            is24x7: true,
            status: "OPERATIONAL"
        },
        {
            id: 2,
            facilityName: "King Edward Memorial (KEM) Hospital & Trauma Unit",
            type: "HOSPITAL",
            state: "Maharashtra",
            city: "Mumbai",
            streetName: "Acharya Donde Marg, Parel",
            zone: "South Mumbai",
            address: "Acharya Donde Marg, Parel, Mumbai",
            pincode: "400012",
            lat: 19.0020,
            lng: 72.8420,
            emergencyContact: "102 / +91-22-24107000",
            ambulanceContact: "+91-22-24107100",
            availableIcuBeds: 38,
            is24x7: true,
            status: "OPERATIONAL"
        },
        {
            id: 3,
            facilityName: "Sawai Man Singh (SMS) Government Hospital",
            type: "HOSPITAL",
            state: "Rajasthan",
            city: "Jaipur",
            streetName: "JLN Marg, Ashok Nagar",
            zone: "Central Jaipur",
            address: "Jawahar Lal Nehru Marg, Ashok Nagar, Jaipur",
            pincode: "302004",
            lat: 26.8990,
            lng: 75.8150,
            emergencyContact: "102 / +91-141-2560291",
            ambulanceContact: "+91-141-2560292",
            availableIcuBeds: 32,
            is24x7: true,
            status: "OPERATIONAL"
        },
        {
            id: 4,
            facilityName: "Sir Sunderlal Hospital & BHU Apex Trauma Center",
            type: "HOSPITAL",
            state: "Uttar Pradesh",
            city: "Varanasi",
            streetName: "Banaras Hindu University Campus, Lanka",
            zone: "South Varanasi",
            address: "BHU Campus, Lanka Road, Varanasi",
            pincode: "221005",
            lat: 25.2750,
            lng: 82.9980,
            emergencyContact: "102 / +91-542-2369000",
            ambulanceContact: "+91-542-2369100",
            availableIcuBeds: 28,
            is24x7: true,
            status: "OPERATIONAL"
        },
        {
            id: 5,
            facilityName: "Victoria Hospital & Bangalore Medical College",
            type: "HOSPITAL",
            state: "Karnataka",
            city: "Bengaluru",
            streetName: "Fort Road, KR Market",
            zone: "Central Bengaluru",
            address: "Fort Road, Near City Market, Bengaluru",
            pincode: "560002",
            lat: 12.9620,
            lng: 77.5750,
            emergencyContact: "102 / +91-80-26701150",
            ambulanceContact: "+91-80-26701151",
            availableIcuBeds: 40,
            is24x7: true,
            status: "OPERATIONAL"
        }
    ],

    grievances: [
        {
            id: 1,
            trackingToken: "GRV-2026-8901",
            citizenName: "Aarav Sharma",
            citizenPhone: "+91-9811122334",
            citizenEmail: "aarav.sharma@example.com",
            state: "Delhi (NCR)",
            city: "New Delhi",
            streetName: "Chandni Chowk Main Road",
            category: "ROAD_POTHOLE",
            title: "Severe Road Depression near Metro Pillar 142",
            description: "Deep asphalt depression causing dangerous sudden braking and two-wheeler skid hazards during night hours.",
            zone: "North Delhi",
            locationAddress: "Sector 14 Main Road, near Metro Pillar 142",
            status: "DISPATCHED",
            priority: "HIGH",
            assignedDepartment: "Public Works Department (PWD)",
            officerNotes: "PWD Road Repair Gang #4 dispatched with asphalt mixer. Expected completion by 5 PM.",
            submittedAt: "2026-08-15 09:30 AM"
        },
        {
            id: 2,
            trackingToken: "GRV-2026-8902",
            citizenName: "Pooja Nair",
            citizenPhone: "+91-9877766554",
            citizenEmail: "pooja.nair@example.com",
            state: "Maharashtra",
            city: "Mumbai",
            streetName: "Linking Road, Bandra West",
            category: "STREET_LIGHT",
            title: "Dark Stretch - 5 Non-Functional LED Poles",
            description: "Street lighting fixture array is out since 3 days on the bypass road, creating safety issues for pedestrians.",
            zone: "Western Suburbs",
            locationAddress: "Linking Road Junction, Bandra West",
            status: "RESOLVED",
            priority: "MEDIUM",
            assignedDepartment: "City Electricity & Energy Board",
            officerNotes: "Main breaker reset and faulty LED drivers replaced at pole #12 through #16.",
            submittedAt: "2026-08-14 07:15 PM"
        },
        {
            id: 3,
            trackingToken: "GRV-2026-8903",
            citizenName: "Vikram Singh",
            citizenPhone: "+91-9988112233",
            citizenEmail: "vikram.s@example.com",
            state: "Rajasthan",
            city: "Jaipur",
            streetName: "Johari Bazaar Road",
            category: "GARBAGE_COLLECTION",
            title: "Overflowing Smart Bin at Johari Bazaar",
            description: "Commercial bazaar waste receptacle overflowing into the walking track. Needs urgent clearance by sanitation squad.",
            zone: "Heritage Core",
            locationAddress: "Near Sanganeri Gate, Johari Bazaar, Jaipur",
            status: "IN_REVIEW",
            priority: "MEDIUM",
            assignedDepartment: "Smart Waste & Sanitation Board",
            officerNotes: "Route compactor truck scheduled for pickup.",
            submittedAt: "2026-08-16 08:20 AM"
        }
    ],

    events: [
        {
            id: 1,
            title: "National Smart City & IoT Clean Energy Summit 2026",
            category: "Technology & Innovation",
            organizer: "Ministry of Housing and Urban Affairs & Smart City Mission",
            state: "Delhi (NCR)",
            city: "New Delhi",
            streetName: "Bharat Mandapam, Pragati Maidan",
            venueName: "Auditorium Plenary Hall, Bharat Mandapam",
            zone: "Central Delhi",
            startDate: "2026-09-10 09:30 AM",
            endDate: "2026-09-12 06:00 PM",
            entryFee: 0.00,
            totalSeats: 1500,
            bookedSeats: 890,
            description: "National flagship conference bringing together urban planners, IoT inventors, and green transport startups across 100 Indian Smart Cities.",
            bannerImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=80",
            status: "UPCOMING"
        },
        {
            id: 2,
            title: "All-India Heritage Food & Street Craft Carnival",
            category: "Culture & Food",
            organizer: "India Tourism Development Corporation (ITDC)",
            state: "Rajasthan",
            city: "Jaipur",
            streetName: "Jawahar Kala Kendra Marg",
            venueName: "Open Air Amphitheatre, Jawahar Kala Kendra",
            zone: "Central Jaipur",
            startDate: "2026-09-18 04:00 PM",
            endDate: "2026-09-21 11:00 PM",
            entryFee: 150.00,
            totalSeats: 2500,
            bookedSeats: 1640,
            description: "Grand cultural feast featuring master chefs from 28 states, live block printing workshops, Rajasthani puppet theatre, and sufi musical nights.",
            bannerImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=80",
            status: "UPCOMING"
        },
        {
            id: 3,
            title: "Mumbai Green Coastal Marathon 2026 (10K / 21K / 42K)",
            category: "Sports & Health",
            organizer: "Maharashtra Department of Sports & Youth Affairs",
            state: "Maharashtra",
            city: "Mumbai",
            streetName: "Marine Drive Coastal Promenade",
            venueName: "Starts at Nariman Point Waterfront",
            zone: "South Mumbai",
            startDate: "2026-10-04 05:30 AM",
            endDate: "2026-10-04 11:30 AM",
            entryFee: 250.00,
            totalSeats: 5000,
            bookedSeats: 3950,
            description: "Run along Mumbai's scenic Arabian Sea coast for zero carbon awareness. Includes timing chip, hydration points, and organic breakfast buffet.",
            bannerImage: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=1000&q=80",
            status: "UPCOMING"
        }
    ]
};
